#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Catcher.Finance.APP.Resource", IsApplication=true)]

namespace Catcher.Finance.APP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int typeSpinner = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04002c
			public const int aliceblue = 2130968620;
			
			// aapt resource value: 0x7f040022
			public const int antiquewhite = 2130968610;
			
			// aapt resource value: 0x7f040082
			public const int aqua = 2130968706;
			
			// aapt resource value: 0x7f040063
			public const int aquamarine = 2130968675;
			
			// aapt resource value: 0x7f04002a
			public const int azure = 2130968618;
			
			// aapt resource value: 0x7f040027
			public const int beige = 2130968615;
			
			// aapt resource value: 0x7f04000d
			public const int bisque = 2130968589;
			
			// aapt resource value: 0x7f040091
			public const int black = 2130968721;
			
			// aapt resource value: 0x7f04000b
			public const int blanchedalmond = 2130968587;
			
			// aapt resource value: 0x7f04008d
			public const int blue = 2130968717;
			
			// aapt resource value: 0x7f04005b
			public const int blueviolet = 2130968667;
			
			// aapt resource value: 0x7f040050
			public const int brown = 2130968656;
			
			// aapt resource value: 0x7f040034
			public const int burlywood = 2130968628;
			
			// aapt resource value: 0x7f040071
			public const int cadetblue = 2130968689;
			
			// aapt resource value: 0x7f040064
			public const int chartreuse = 2130968676;
			
			// aapt resource value: 0x7f04003f
			public const int chocolate = 2130968639;
			
			// aapt resource value: 0x7f040017
			public const int coral = 2130968599;
			
			// aapt resource value: 0x7f040070
			public const int cornflowerblue = 2130968688;
			
			// aapt resource value: 0x7f040007
			public const int cornsilk = 2130968583;
			
			// aapt resource value: 0x7f040037
			public const int crimson = 2130968631;
			
			// aapt resource value: 0x7f040083
			public const int cyan = 2130968707;
			
			// aapt resource value: 0x7f04008f
			public const int darkblue = 2130968719;
			
			// aapt resource value: 0x7f040089
			public const int darkcyan = 2130968713;
			
			// aapt resource value: 0x7f040047
			public const int darkgoldenrod = 2130968647;
			
			// aapt resource value: 0x7f04004e
			public const int darkgray = 2130968654;
			
			// aapt resource value: 0x7f04008c
			public const int darkgreen = 2130968716;
			
			// aapt resource value: 0x7f04004f
			public const int darkgrey = 2130968655;
			
			// aapt resource value: 0x7f040044
			public const int darkkhaki = 2130968644;
			
			// aapt resource value: 0x7f040059
			public const int darkmagenta = 2130968665;
			
			// aapt resource value: 0x7f040072
			public const int darkolivegreen = 2130968690;
			
			// aapt resource value: 0x7f040016
			public const int darkorange = 2130968598;
			
			// aapt resource value: 0x7f040052
			public const int darkorchid = 2130968658;
			
			// aapt resource value: 0x7f04005a
			public const int darkred = 2130968666;
			
			// aapt resource value: 0x7f040031
			public const int darksalmon = 2130968625;
			
			// aapt resource value: 0x7f040057
			public const int darkseagreen = 2130968663;
			
			// aapt resource value: 0x7f040075
			public const int darkslateblue = 2130968693;
			
			// aapt resource value: 0x7f04007b
			public const int darkslategray = 2130968699;
			
			// aapt resource value: 0x7f04007c
			public const int darkslategrey = 2130968700;
			
			// aapt resource value: 0x7f040087
			public const int darkturquoise = 2130968711;
			
			// aapt resource value: 0x7f040054
			public const int darkviolet = 2130968660;
			
			// aapt resource value: 0x7f04001b
			public const int deeppink = 2130968603;
			
			// aapt resource value: 0x7f040088
			public const int deepskyblue = 2130968712;
			
			// aapt resource value: 0x7f04006d
			public const int dimgray = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int dimgrey = 2130968686;
			
			// aapt resource value: 0x7f040080
			public const int dodgerblue = 2130968704;
			
			// aapt resource value: 0x7f040048
			public const int firebrick = 2130968648;
			
			// aapt resource value: 0x7f040005
			public const int floralwhite = 2130968581;
			
			// aapt resource value: 0x7f04007e
			public const int forestgreen = 2130968702;
			
			// aapt resource value: 0x7f04001c
			public const int fuchsia = 2130968604;
			
			// aapt resource value: 0x7f040036
			public const int gainsboro = 2130968630;
			
			// aapt resource value: 0x7f040024
			public const int ghostwhite = 2130968612;
			
			// aapt resource value: 0x7f040011
			public const int gold = 2130968593;
			
			// aapt resource value: 0x7f040039
			public const int goldenrod = 2130968633;
			
			// aapt resource value: 0x7f04005e
			public const int gray = 2130968670;
			
			// aapt resource value: 0x7f04008b
			public const int green = 2130968715;
			
			// aapt resource value: 0x7f04004c
			public const int greenyellow = 2130968652;
			
			// aapt resource value: 0x7f04005f
			public const int grey = 2130968671;
			
			// aapt resource value: 0x7f04002b
			public const int honeydew = 2130968619;
			
			// aapt resource value: 0x7f040018
			public const int hotpink = 2130968600;
			
			// aapt resource value: 0x7f040041
			public const int indianred = 2130968641;
			
			// aapt resource value: 0x7f040073
			public const int indigo = 2130968691;
			
			// aapt resource value: 0x7f040001
			public const int ivory = 2130968577;
			
			// aapt resource value: 0x7f04002d
			public const int khaki = 2130968621;
			
			// aapt resource value: 0x7f040032
			public const int lavender = 2130968626;
			
			// aapt resource value: 0x7f040009
			public const int lavenderblush = 2130968585;
			
			// aapt resource value: 0x7f040065
			public const int lawngreen = 2130968677;
			
			// aapt resource value: 0x7f040006
			public const int lemonchiffon = 2130968582;
			
			// aapt resource value: 0x7f04004d
			public const int lightblue = 2130968653;
			
			// aapt resource value: 0x7f04002e
			public const int lightcoral = 2130968622;
			
			// aapt resource value: 0x7f040033
			public const int lightcyan = 2130968627;
			
			// aapt resource value: 0x7f040020
			public const int lightgoldenrodyellow = 2130968608;
			
			// aapt resource value: 0x7f04003c
			public const int lightgray = 2130968636;
			
			// aapt resource value: 0x7f040056
			public const int lightgreen = 2130968662;
			
			// aapt resource value: 0x7f04003d
			public const int lightgrey = 2130968637;
			
			// aapt resource value: 0x7f040013
			public const int lightpink = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int lightsalmon = 2130968597;
			
			// aapt resource value: 0x7f04007f
			public const int lightseagreen = 2130968703;
			
			// aapt resource value: 0x7f04005c
			public const int lightskyblue = 2130968668;
			
			// aapt resource value: 0x7f040067
			public const int lightslategray = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int lightslategrey = 2130968680;
			
			// aapt resource value: 0x7f04004a
			public const int lightsteelblue = 2130968650;
			
			// aapt resource value: 0x7f040002
			public const int lightyellow = 2130968578;
			
			// aapt resource value: 0x7f040085
			public const int lime = 2130968709;
			
			// aapt resource value: 0x7f04007a
			public const int limegreen = 2130968698;
			
			// aapt resource value: 0x7f040021
			public const int linen = 2130968609;
			
			// aapt resource value: 0x7f04001d
			public const int magenta = 2130968605;
			
			// aapt resource value: 0x7f040062
			public const int maroon = 2130968674;
			
			// aapt resource value: 0x7f04006f
			public const int mediumaquamarine = 2130968687;
			
			// aapt resource value: 0x7f04008e
			public const int mediumblue = 2130968718;
			
			// aapt resource value: 0x7f040046
			public const int mediumorchid = 2130968646;
			
			// aapt resource value: 0x7f040055
			public const int mediumpurple = 2130968661;
			
			// aapt resource value: 0x7f040079
			public const int mediumseagreen = 2130968697;
			
			// aapt resource value: 0x7f040066
			public const int mediumslateblue = 2130968678;
			
			// aapt resource value: 0x7f040086
			public const int mediumspringgreen = 2130968710;
			
			// aapt resource value: 0x7f040074
			public const int mediumturquoise = 2130968692;
			
			// aapt resource value: 0x7f040042
			public const int mediumvioletred = 2130968642;
			
			// aapt resource value: 0x7f040081
			public const int midnightblue = 2130968705;
			
			// aapt resource value: 0x7f040025
			public const int mintcream = 2130968613;
			
			// aapt resource value: 0x7f04000c
			public const int mistyrose = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int moccasin = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int navajowhite = 2130968591;
			
			// aapt resource value: 0x7f040090
			public const int navy = 2130968720;
			
			// aapt resource value: 0x7f04001f
			public const int oldlace = 2130968607;
			
			// aapt resource value: 0x7f040060
			public const int olive = 2130968672;
			
			// aapt resource value: 0x7f04006b
			public const int olivedrab = 2130968683;
			
			// aapt resource value: 0x7f040014
			public const int orange = 2130968596;
			
			// aapt resource value: 0x7f04001a
			public const int orangered = 2130968602;
			
			// aapt resource value: 0x7f04003a
			public const int orchid = 2130968634;
			
			// aapt resource value: 0x7f04002f
			public const int palegoldenrod = 2130968623;
			
			// aapt resource value: 0x7f040053
			public const int palegreen = 2130968659;
			
			// aapt resource value: 0x7f04004b
			public const int paleturquoise = 2130968651;
			
			// aapt resource value: 0x7f040038
			public const int palevioletred = 2130968632;
			
			// aapt resource value: 0x7f04000a
			public const int papayawhip = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int peachpuff = 2130968592;
			
			// aapt resource value: 0x7f040040
			public const int peru = 2130968640;
			
			// aapt resource value: 0x7f040012
			public const int pink = 2130968594;
			
			// aapt resource value: 0x7f040035
			public const int plum = 2130968629;
			
			// aapt resource value: 0x7f040049
			public const int powderblue = 2130968649;
			
			// aapt resource value: 0x7f040061
			public const int purple = 2130968673;
			
			// aapt resource value: 0x7f04001e
			public const int red = 2130968606;
			
			// aapt resource value: 0x7f040045
			public const int rosybrown = 2130968645;
			
			// aapt resource value: 0x7f040077
			public const int royalblue = 2130968695;
			
			// aapt resource value: 0x7f040058
			public const int saddlebrown = 2130968664;
			
			// aapt resource value: 0x7f040023
			public const int salmon = 2130968611;
			
			// aapt resource value: 0x7f040029
			public const int sandybrown = 2130968617;
			
			// aapt resource value: 0x7f04007d
			public const int seagreen = 2130968701;
			
			// aapt resource value: 0x7f040008
			public const int seashell = 2130968584;
			
			// aapt resource value: 0x7f040051
			public const int sienna = 2130968657;
			
			// aapt resource value: 0x7f040043
			public const int silver = 2130968643;
			
			// aapt resource value: 0x7f04005d
			public const int skyblue = 2130968669;
			
			// aapt resource value: 0x7f04006c
			public const int slateblue = 2130968684;
			
			// aapt resource value: 0x7f040069
			public const int slategray = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int slategrey = 2130968682;
			
			// aapt resource value: 0x7f040004
			public const int snow = 2130968580;
			
			// aapt resource value: 0x7f040084
			public const int springgreen = 2130968708;
			
			// aapt resource value: 0x7f040076
			public const int steelblue = 2130968694;
			
			// aapt resource value: 0x7f04003e
			public const int tan = 2130968638;
			
			// aapt resource value: 0x7f04008a
			public const int teal = 2130968714;
			
			// aapt resource value: 0x7f04003b
			public const int thistle = 2130968635;
			
			// aapt resource value: 0x7f040019
			public const int tomato = 2130968601;
			
			// aapt resource value: 0x7f040078
			public const int turquoise = 2130968696;
			
			// aapt resource value: 0x7f040030
			public const int violet = 2130968624;
			
			// aapt resource value: 0x7f040028
			public const int wheat = 2130968616;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f040026
			public const int whitesmoke = 2130968614;
			
			// aapt resource value: 0x7f040003
			public const int yellow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int clock = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int list = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int loginpwd = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int loginuser = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int service = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09003b
			public const int btnReg = 2131296315;
			
			// aapt resource value: 0x7f090017
			public const int btn_addItem = 2131296279;
			
			// aapt resource value: 0x7f090021
			public const int btn_login = 2131296289;
			
			// aapt resource value: 0x7f090037
			public const int btn_reg = 2131296311;
			
			// aapt resource value: 0x7f09002e
			public const int btn_updatePersonal = 2131296302;
			
			// aapt resource value: 0x7f09000b
			public const int ed_date = 2131296267;
			
			// aapt resource value: 0x7f090016
			public const int et_about = 2131296278;
			
			// aapt resource value: 0x7f090035
			public const int et_email = 2131296309;
			
			// aapt resource value: 0x7f090014
			public const int et_money = 2131296276;
			
			// aapt resource value: 0x7f09002f
			public const int et_name = 2131296303;
			
			// aapt resource value: 0x7f090036
			public const int et_pwd = 2131296310;
			
			// aapt resource value: 0x7f09002c
			public const int et_uEmail = 2131296300;
			
			// aapt resource value: 0x7f090027
			public const int et_uName = 2131296295;
			
			// aapt resource value: 0x7f090023
			public const int framelayout_Show = 2131296291;
			
			// aapt resource value: 0x7f09001e
			public const int img_mainLogo = 2131296286;
			
			// aapt resource value: 0x7f090038
			public const int img_welcomeLogo = 2131296312;
			
			// aapt resource value: 0x7f09000c
			public const int imgbtn_date = 2131296268;
			
			// aapt resource value: 0x7f09001d
			public const int lid = 2131296285;
			
			// aapt resource value: 0x7f090009
			public const int linearLayout1 = 2131296265;
			
			// aapt resource value: 0x7f09001a
			public const int linearLayout2 = 2131296282;
			
			// aapt resource value: 0x7f09002a
			public const int linearLayout3 = 2131296298;
			
			// aapt resource value: 0x7f09002d
			public const int linearLayout4 = 2131296301;
			
			// aapt resource value: 0x7f09000d
			public const int ll_category = 2131296269;
			
			// aapt resource value: 0x7f090010
			public const int ll_type = 2131296272;
			
			// aapt resource value: 0x7f090018
			public const int lv_detial = 2131296280;
			
			// aapt resource value: 0x7f09001c
			public const int lv_service = 2131296284;
			
			// aapt resource value: 0x7f090008
			public const int lv_tv_about = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int lv_tv_category = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int lv_tv_date = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int lv_tv_money = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int lv_tv_type = 2131296262;
			
			// aapt resource value: 0x7f090022
			public const int menuGroup = 2131296290;
			
			// aapt resource value: 0x7f090024
			public const int rbtn_addItem = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int rbtn_itemDetial = 2131296293;
			
			// aapt resource value: 0x7f090032
			public const int rbtn_man = 2131296306;
			
			// aapt resource value: 0x7f090026
			public const int rbtn_service = 2131296294;
			
			// aapt resource value: 0x7f090033
			public const int rbtn_woman = 2131296307;
			
			// aapt resource value: 0x7f090031
			public const int rdg_gender = 2131296305;
			
			// aapt resource value: 0x7f09000f
			public const int sp_category = 2131296271;
			
			// aapt resource value: 0x7f090012
			public const int sp_type = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int textView1 = 2131296275;
			
			// aapt resource value: 0x7f090028
			public const int textView2 = 2131296296;
			
			// aapt resource value: 0x7f09002b
			public const int textView3 = 2131296299;
			
			// aapt resource value: 0x7f090000
			public const int tv_about = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int tv_aboutAuthor = 2131296257;
			
			// aapt resource value: 0x7f090039
			public const int tv_appName = 2131296313;
			
			// aapt resource value: 0x7f09000a
			public const int tv_date = 2131296266;
			
			// aapt resource value: 0x7f090019
			public const int tv_income = 2131296281;
			
			// aapt resource value: 0x7f090003
			public const int tv_lv5 = 2131296259;
			
			// aapt resource value: 0x7f09001b
			public const int tv_pay = 2131296283;
			
			// aapt resource value: 0x7f090029
			public const int tv_uGender = 2131296297;
			
			// aapt resource value: 0x7f09003a
			public const int tv_version = 2131296314;
			
			// aapt resource value: 0x7f09000e
			public const int tx_category = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int tx_type = 2131296273;
			
			// aapt resource value: 0x7f090015
			public const int txt_about = 2131296277;
			
			// aapt resource value: 0x7f090034
			public const int txt_email = 2131296308;
			
			// aapt resource value: 0x7f090030
			public const int txt_gender = 2131296304;
			
			// aapt resource value: 0x7f09001f
			public const int txt_name = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int txt_pwd = 2131296288;
			
			// aapt resource value: 0x7f090002
			public const int wv_author = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int author = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int detiallistview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_addItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_detial = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_service = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int personal = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int reg = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int welcome = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int domain = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int basetheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int windowTitleBackgroundStyle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int windowTitleStyle = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
